config/routes.rb
Rails.application.routes.draw do

  resources :activities

  resources :pictures
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
      post :reply
      post :restore
      post :mark_as_read
      post :mark_as_unread
    end
  end

  resources :messages, only: [:new, :create]

  resources :bandtogethers
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}

  resources :relationships, only: [:create, :destroy]

  resources :concerts do
      get 'map_location'
    end

  resources :users do
    member do
      get :following, :followers
    end
  end

  mount Commontator::Engine => '/commontator'

  get 'relationships', to: 'relationships#create'

  get '/bandtogethers/:id/join(.:format)' => 'users#join'
  get '/bandtogethers/:id/leave(.:format)' => 'users#leave'
  get '/bandtogethers/:id/invite' => 'bandtogethers#invite'

  get '/pages/about' => 'pages#show'

  authenticated do
    root :to => 'dashboard#index', as: :authenticated
  end

  root 'concerts#index'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  # to include get_unread_count
  include ApplicationHelper
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]
  #counts unread emails in current user inbox
  before_action :get_unread_count

 def index
   if @box.eql? "inbox"
    @conversations = @mailbox.inbox
  elsif @box.eql? "sent"
    @conversations = @mailbox.sentbox
  else
    @conversations = @mailbox.trash
  end
  @conversations = @conversations.paginate(page: params[:page], per_page: 10)
 end

 def show
   if @conversation.is_unread?(current_user)
    @conversation.mark_as_read(current_user)
    @messages_count = @messages_count - 1
    end
 end

 def reply
   current_user.reply_to_conversation(@conversation, params[:body])
   flash[:success] = 'Reply sent'
   redirect_to conversation_path(@conversation)
 end

 def destroy
   @conversation.move_to_trash(current_user)
   flash[:success] = 'The conversation was moved to trash.'
   redirect_to conversations_path
 end

 def restore
   @conversation.untrash(current_user)
   flash[:success] = 'The conversation was restored.'
   redirect_to conversations_path
 end

 def empty_trash

  @mailbox.trash.each do |conversation|
    conversation.receipts_for(current_user).update_all(deleted: true)
  end
  flash[:success] = 'Your trash was cleaned!'
  redirect_to conversations_path
end

def mark_as_read
  @conversation.mark_as_read(current_user)
  flash[:success] = 'The conversation was marked as read.'
  redirect_to conversations_path
end

def mark_as_unread
  @conversation.mark_as_unread(current_user)
  flash[:success] = 'The conversation was marked as unread.'
  redirect_to conversations_path
end









 private

 def get_mailbox
   @mailbox ||= current_user.mailbox
 end

 def get_conversation
   @conversation ||= @mailbox.conversations.find(params[:id])
 end

 def get_box
  if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
    params[:box] = 'inbox'
  end
  @box = params[:box]
  end


end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
  <li class="list-group-item clearfix">
    <% if conversation.is_unread?(current_user) %>
  <strong><%= link_to conversation.subject, conversation_path(conversation) %></strong>
  <%else%>
  <%= link_to conversation.subject, conversation_path(conversation) %>
  <%end%>
  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>

      <% if @box == 'inbox'%>
      <% if conversation.is_unread?(current_user) %>
      <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                class: 'btn btn-xs btn-info', method: :post %>

      <% end %>
      <% if !conversation.is_unread?(current_user) %>
      <%= link_to 'Mark as unread', mark_as_unread_conversation_path(conversation),
                class: 'btn btn-xs btn-info', method: :post %>
      <% end %>
      <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, conversation_path(conversation), class: 'btn btn-xs btn-danger', id:"put_in_trash", method: :delete,
                  data: {confirm: 'Are you sure?'} %>
    <% end %>
    <% end %>
  </div>

  <p><%= render 'conversations/participants', conversation: conversation %></p>

  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <% if !participant.avatar_file_name.nil? %>
    <%= image_tag(participant.avatar.url(:thumb)) %>
    <% end %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<h1>Your Conversations</h1>

<div class="row">
  <div class="col-sm-3">
    <ul class="nav nav-pills nav-stacked">
      <%= mailbox_section 'inbox', @box %>
      <%= mailbox_section 'sent', @box %>
      <%= mailbox_section 'trash', @box %>
    </ul>
  </div>

  <div class="col-sm-9">
    <% if @box == 'trash' %>
    <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                   data: {confirm: 'Are you sure?'} %></p>
    <%end%>
    <ul class="list-group">
      <%= render partial: 'conversations/conversation', collection: @conversations %>
    </ul>

    <%= will_paginate %>
  </div>
</div>

app/views/conversations/show.html.erb
<h1>Conversation</h1>

<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <% message = receipt.message %>
        <br>
        <a href="/users/<%=message.sender.id%>"><%= message.sender.first_name %> <%=message.sender.last_name %></a>

        <br>
          says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %>
          <br>
          <br>
        <%= message.body %>
        <br><hr>
      <% end %>
    </div>
  </div>
</div>

<%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-default' %>
<% end %>