config/routes.rb
Rails.application.routes.draw do

  resources :activities

  resources :pictures
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
      post :reply
      post :restore
      post :mark_as_read
      post :mark_as_unread
    end
  end

  resources :messages, only: [:new, :create]

  resources :bandtogethers
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}

  resources :relationships, only: [:create, :destroy]

  resources :concerts do
      get 'map_location'
    end

  resources :users do
    member do
      get :following, :followers
    end
  end

  mount Commontator::Engine => '/commontator'

  get 'relationships', to: 'relationships#create'

  get '/bandtogethers/:id/join(.:format)' => 'users#join'
  get '/bandtogethers/:id/leave(.:format)' => 'users#leave'
  get '/bandtogethers/:id/invite' => 'bandtogethers#invite'

  get '/pages/about' => 'pages#show'

  authenticated do
    root :to => 'dashboard#index', as: :authenticated
  end

  root 'concerts#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :capitalize_names
  resourcify

  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  # Relationship

  has_many :active_relationships,  class_name:  "Relationship", foreign_key: "follower_id", dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship", foreign_key: "followed_id", dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower




  #commontator
  acts_as_commontator
  acts_as_commontable


  acts_as_messageable


# membership/organizer relationship
has_many :bandtogethers_as_organizer, :class_name => 'Bandtogether', :foreign_key => 'organizer_id', dependent: :destroy
has_many :bandtogethers, through: :memberships
has_many :memberships, dependent: :destroy

  #paperclip

has_many :pictures, dependent: :destroy

  has_attached_file :avatar, :styles => { :large => "300x300>", :medium => "90x90>", :thumb => "50x50#"}, :default_url => "/images/:style/default_avatar.jpg"

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  # validations
  validates :first_name, length: { minimum: 2 }
  validates :last_name, length: { minimum: 2 }

  validates_presence_of :first_name
  validates_presence_of :last_name


  def capitalize_names
    self.first_name = first_name.camelcase
    self.last_name = last_name.camelcase
  end


  # helpers methods

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  attr_accessor :current_password

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name   # assuming the user model has a name
      user.last_name = auth.info.last_name

      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def mailboxer_email(object)
    email
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # to include get_unread_count
  include ApplicationHelper
  before_action :current_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  #counts unread emails in current user inbox
  before_action :get_unread_count

  def index
    if user_signed_in?
       if params[:search].nil? || params[:search].empty?
          @users = User.order('created_at DESC').paginate(page: params[:page], per_page: 30)
       else
         @users = User.search(params[:search]).order('created_at DESC').paginate(page: params[:page], per_page: 30)
       end
    else
      redirect_to '/'
    end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = User.all





    render 'show_following'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = User.all
    render 'show_follow'
  end

  def join
    @user = current_user
    # @bandtogether set to bandtogether on current page
    @bandtogether = Bandtogether.find(params[:id])
    # @membership set to membership matching the bandtogether on current page and mapping all members

    @membership = Membership.where(bandtogether_id: @bandtogether.id).map {|membership| membership.user_id}
    # if the current user's id is NOT in the membership array, add it and redirect to bandtogether page.
    if !@membership.include?(@user.id)
      @user.bandtogethers << @bandtogether
      redirect_to "/bandtogethers/" + @bandtogether.id.to_s
    # if the current user's id IS in the membership array,  redirect to bandtogether page.
    else
      redirect_to "/bandtogethers/" + @bandtogether.id.to_s
    end
  end

  def leave
    @user = current_user
    # @bandtogether set to bandtogether on current page
    @bandtogether = Bandtogether.find(params[:id])
    # @membership set to membership matching the bandtogether on current page and mapping all members
    @membership = Membership.where(bandtogether_id: @bandtogether.id).map {|membership| membership.user_id}
    # if the current user's id is NOT in the membership array, add it and redirect to bandtogether page.
    if @membership.include?(@user.id)
      @user.bandtogethers.delete(@bandtogether)
      redirect_to "/bandtogethers/" + @bandtogether.id.to_s
    # if the current user's id IS in the membership array,  redirect to bandtogether page.
    else
      redirect_to "/bandtogethers/" + @bandtogether.id.to_s
    end
  end

  def show
    if user_signed_in?
      @user = User.find(params[:id])
      @pictures = @user.pictures
      @bandtogethers = Bandtogether.where(organizer_id: @user.id)
      @concerts_for_select = Concert.all.map do |concert|
        [concert.title, concert.id]
      end
    else
      redirect_to '/'
    end
  end

  def destroy
    if current_user.has_role? :admin
      @user = User.find(params[:id])
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-default" %>
<% end %>

app/views/users/_join.html.erb
<form action="/bandtogethers/<%= @bandtogether.id %>/join" method="patch">
  <input class="btn btn-default invite-join-buttons" type="submit" value="Join">

</form>

app/views/users/_leave.html.erb
<form action="/bandtogethers/<%= @bandtogether.id %>/leave" method="get">
  <input class="btn btn-default invite-join-buttons" type="submit" value="Leave">

</form>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/index.html.erb
</div>


<div class="jumbotron users_jumbo">
    <div class="jumbo col-sm-5">
      <div class="jumbo col-sm-5">
        <h1>Bandies</h1>
      </div>
    </div>

</div>

<div class="container">

<form action="/users" method="get">
 <input type="text" name="search">
 <input type="submit" value="Search">
</form>

<table class = "table">
  <thead>
      <tr>
        <th>Profile Picture</th>
        <th>Name</th>
        <th>Location</th>
        <th> Artists</th>
      </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><% if !user.avatar_file_name.nil? %>
        <%= image_tag(user.avatar.url(:thumb)) %>
      <% end %> </td>
      <td><a href='users/<%=user.id%>'><%= user.first_name%> <%= user.last_name%></a>
      </td>
      <td>
        <% if user.city.present? && user.state.present? %>
          <% if !user.city.nil? || !user.state.nil? %>
            <%= [user.city, user.state].join(', ')%>
          <% end %>
        <% end %>
      </td>

      <td><%=user.artists%></td>

      <td>
         <!-- <%= render 'shared/stats' %> -->
      </td>
      <% if !current_user.nil? %>
      <% if current_user.has_role? :admin %>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="panel panel-default">
<div class="row">
<div class="col-sm-7">
  <p id="notice"><%= notice %></p>

<h2><%=@user.first_name%> <%=@user.last_name%></h2>

<% if current_user.city.present? && current_user.state.present? %>
  <% if !current_user.city.nil? || !current_user.state.nil? %>
    <h3> <%= [current_user.city, current_user.state].join(', ')%></h3>
  <% end %>
<% end %>


<section class="stats">
   <%= render 'shared/stats' %>
 </section>
 <br>
<%= render 'components/follow_button' if user_signed_in? %>
<br>
<% unless current_user == @user %>
       <%= link_to 'Send message', new_message_path(to: @user.id), class: 'btn btn-default btn-sm' %>
    <%end%>

<br>
<% if @user == current_user %>
  <%= link_to 'Edit Profile', edit_user_registration_path %>
<% end %>
<br>





<h4>Email</h4>
<h5><%=@user.email%></h5>

<% if !@user.age.nil? %>
  <h4>Age</h4>
  <h5><%=@user.age%></h5>
<% end %>


<% if !@user.gender.nil? %>
  <% if !@user.gender.empty? %>
    <h4>Gender</h4>
    <h5><%=@user.gender%></h5>
  <% end %>
<% end %>

<% if !@user.postal_code.nil? %>
  <h4>Postal Code</h4>
  <h5><%=@user.postal_code%></h5>
<% end %>

<% if !@user.about.nil? %>
  <% if !@user.about.empty? %>
    <h4>About Me</h4>
    <h5><%=@user.about%></h5>
  <% end %>
<% end %>


<% if !@user.artists.nil? %>
  <% if !@user.artists.empty? %>
    <h4>Favorite Artists</h4>
    <h5><%=@user.artists%></h5>
  <% end %>
<% end %>
</div>
<div class="col-sm-5">
<% if !@user.avatar_file_name.nil? %>
  <%= image_tag(@user.avatar.url(:large)) %>
<% end %>
</div>
</div>
<br>
<br>

  <%=render_gallery_for @pictures%>


<% if !@bandtogethers.empty? %>

  <div class="clearfix">
  <h3> <%=@user.first_name%>'s Bandtogethers</h3>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Start time</th>
        <th>End time</th>
        <th>Description</th>
        <th>Concert</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @bandtogethers.each do |bandtogether| %>
        <tr>
          <td><%=link_to bandtogether.title, bandtogether %></td>
          <td><%= bandtogether.start_time %></td>
          <td><%= bandtogether.end_time %></td>
          <td><%= bandtogether.description %></td>
          <td><%= bandtogether.concert.title %></td>
          <% if @user == current_user %>
            <td><%= link_to 'Edit', edit_bandtogether_path(bandtogether) %></td>
            <td><%= link_to 'Destroy', bandtogether, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end%>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-2">
    <section class="user_info">
      <h1><%= @user.first_name %></h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-10">
    <h2><%= @title %></h2>
    <table>
      <tbody>
        <% @user.followers.each do |follower| %>
        <tr>
          <td><h4><a href="/users/<%=follower.id%>"> <%=follower.first_name%> <%=follower.last_name%> </a></h4></td>
        </tr>
        <% end %>

    </tbody>
  </table>
  </div>
</div>

app/views/users/show_following.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-2">
    <section class="user_info">
      <h1><%= @user.first_name %></h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-10">
    <h2><%= @title %></h2>
    <table>
      <tbody>
          <% @user.following.each do |following| %>
          <tr>
            <td><h4><a href="/users/<%=following.id%>"> <%=following.first_name%> <%=following.last_name%> </a></h4></td>
          </tr>
          <% end %>
    </tbody>
  </table>
  </div>
</div>