config/routes.rb
Rails.application.routes.draw do

  resources :activities

  resources :pictures
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
      post :reply
      post :restore
      post :mark_as_read
      post :mark_as_unread
    end
  end

  resources :messages, only: [:new, :create]

  resources :bandtogethers
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}

  resources :relationships, only: [:create, :destroy]

  resources :concerts do
      get 'map_location'
    end

  resources :users do
    member do
      get :following, :followers
    end
  end

  mount Commontator::Engine => '/commontator'

  get 'relationships', to: 'relationships#create'

  get '/bandtogethers/:id/join(.:format)' => 'users#join'
  get '/bandtogethers/:id/leave(.:format)' => 'users#leave'
  get '/bandtogethers/:id/invite' => 'bandtogethers#invite'

  get '/pages/about' => 'pages#show'

  authenticated do
    root :to => 'dashboard#index', as: :authenticated
  end

  root 'concerts#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :user
  has_attached_file :picture, :styles => { :medium => "90x90>", :thumb => "50x50#"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to edit_user_registration_path, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:user_id)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for(@picture, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @picture.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h4>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<div class="page-header">
  <%= link_to pictures_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @picture, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing picture</h1>
</div>

<%= render 'form' %>

app/views/pictures/index.html.erb
<div class="page-header">
  <%= link_to new_picture_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Picture
  <% end %>
  <h1>Listing pictures</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>User</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @pictures) do |picture| %>
            <td><%= picture.user %></td>
            <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pictures/new.html.erb
<div class="page-header">
  <%= link_to pictures_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New picture</h1>
</div>

<%= render 'form' %>

app/views/pictures/show.html.erb
<div class="page-header">
  <%= link_to pictures_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_picture_path(@picture), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show picture</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @picture.user %></dd>

</dl>