config/routes.rb
Rails.application.routes.draw do

  resources :activities

  resources :pictures
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
      post :reply
      post :restore
      post :mark_as_read
      post :mark_as_unread
    end
  end

  resources :messages, only: [:new, :create]

  resources :bandtogethers
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}

  resources :relationships, only: [:create, :destroy]

  resources :concerts do
      get 'map_location'
    end

  resources :users do
    member do
      get :following, :followers
    end
  end

  mount Commontator::Engine => '/commontator'

  get 'relationships', to: 'relationships#create'

  get '/bandtogethers/:id/join(.:format)' => 'users#join'
  get '/bandtogethers/:id/leave(.:format)' => 'users#leave'
  get '/bandtogethers/:id/invite' => 'bandtogethers#invite'

  get '/pages/about' => 'pages#show'

  authenticated do
    root :to => 'dashboard#index', as: :authenticated
  end

  root 'concerts#index'

end

app/models/bandtogether.rb
class Bandtogether < ActiveRecord::Base
  #newsfeed gem
  include PublicActivity::Common
  # tracked owner: ->(controller, model) {controller && controller.current_user}



  resourcify

  belongs_to :concert
  belongs_to :organizer, :class_name => 'User'
  has_many :members, through: :memberships, source: :user
  has_many :memberships, dependent: :destroy

  #commontator gem
  acts_as_commontable
  acts_as_commontator


  validates :title, length: { minimum: 2 }
  validates :description, length: { minimum: 2, maximum: 500 }

  validates_presence_of :title
  validates_presence_of :start_time
  validates_presence_of :end_time
  validates_presence_of :description
  validates_presence_of :concert

  has_attached_file :bandtogether_avatar, :styles => { :medium => "300x300>", :thumb => "50x50#"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :bandtogether_avatar, :content_type => /\Aimage\/.*\Z/


end

app/controllers/bandtogethers_controller.rb
class BandtogethersController < ApplicationController
  # to include get_unread_count
  include ApplicationHelper
  before_action :set_bandtogether, only: [:show, :edit, :update, :destroy]
  #counts unread emails in current user inbox
  before_action :get_unread_count

  # GET /bandtogethers
  # GET /bandtogethers.json
  def index
    @bandtogethers = Bandtogether.all
  end

  # GET /bandtogethers/1
  # GET /bandtogethers/1.json
  def show

    if user_signed_in?
      @user = current_user
      # @bandtogether set to bandtogether on current page
      @bandtogether = Bandtogether.find(params[:id])
      @concert = @bandtogether.concert
      # @membership set to membership matching the bandtogether on current page and mapping all members
      @membership = Membership.where(bandtogether_id: @bandtogether.id).map {|membership| membership.user_id}
    else
       redirect_to '/users/sign_up'
    end
  end

  # GET /bandtogethers/new
  def new
    if user_signed_in?
      @bandtogether = Bandtogether.new
      @upcoming_concerts_for_select = Concert.where("start > ?", Time.now).all.map do |concert|
      [concert.title, concert.id]
      end
      @bandtogether.concert = Concert.first
    else
      redirect_to '/'
    end
  end
  # GET /bandtogethers/1/edit
  def edit
      @bandtogether = Bandtogether.find(params[:id])
    if @bandtogether.organizer_id == current_user.id || current_user.has_role?(:admin)
      @upcoming_concerts_for_select = Concert.where("start > ?", Time.now).all.map do |concert|
        [concert.title, concert.id]
      end
      @bandtogether.concert = Concert.first
    else
      redirect_to '/bandtogethers'
    end
  end

  # POST /bandtogethers
  # POST /bandtogethers.json
  def create
    @bandtogether = Bandtogether.new(bandtogether_params)
    @bandtogether.organizer_id = current_user.id
    @upcoming_concerts_for_select = Concert.where("start > ?", Time.now).all.map do |concert|
      [concert.title, concert.id]
    concert = Concert.where(id: params[:concert])
    @bandtogether.concert = concert[0]
    end

    respond_to do |format|
      if @bandtogether.save
        #add to newsfeed
        @bandtogether.create_activity :create, owner: current_user

        format.html { redirect_to @bandtogether, notice: 'Bandtogether was successfully created.' }
        format.json { render :show, status: :created, location: @bandtogether }
      else
        format.html { render :new }
        format.json { render json: @bandtogether.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bandtogethers/1
  # PATCH/PUT /bandtogethers/1.json
  def update
    respond_to do |format|
      if @bandtogether.update(bandtogether_params)
        #add to newsfeed
        @bandtogether.create_activity :update, owner: current_user

        format.html { redirect_to @bandtogether, notice: 'Bandtogether was successfully updated.' }
        format.json { render :show, status: :ok, location: @bandtogether }
      else
        format.html { render :edit }
        format.json { render json: @bandtogether.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bandtogethers/1
  # DELETE /bandtogethers/1.json
  def destroy
    if @bandtogether.organizer_id == current_user.id
      @bandtogether.destroy
      respond_to do |format|
        format.html { redirect_to bandtogethers_url, notice: 'Bandtogether was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to '/bandtogethers'
    end

  end

  def invite
    @bandtogether = Bandtogether.find(params[:id])
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bandtogether
      @bandtogether = Bandtogether.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bandtogether_params
      params.require(:bandtogether).permit(:title, :start_time, :end_time, :description, :concert_id, :bandtogether_avatar)
    end
end

app/helpers/bandtogethers_helper.rb
module BandtogethersHelper
  def concerts_options
    s = ''
    Concert.all.each do |concert|
      s << "<option value='#{concert.id}'>#{concert.title}</option>"
    end
    s.html_safe
  end

end

app/views/bandtogethers/_form.html.erb
<%= form_for(@bandtogether) do |f| %>
  <% if @bandtogether.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bandtogether.errors.count, "error") %> prohibited this bandtogether from being saved:</h2>

      <ul>
      <% @bandtogether.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
<div class = "row">
  <div class = "col-sm-8">
    <div class="form-group">
      <%= f.label :bandtogether_avatar, class: 'control-label' %>
      <%= f.file_field :bandtogether_avatar, class: "form-control "%>
    </div>

    <div class="form-group">
      <%= f.label :title, class: "control-label" %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :start_time, class: "control-label" %><br>
      <%= f.text_field :start_time, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :end_time, class: "control-label" %><br>
      <%= f.text_field :end_time, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description, class: "control-label" %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>


    <div class="form-group">
      <%= f.label :concert, 'Choose concert' %>
      <%= select_tag 'concert', concerts_options, class: 'form-control chosen-it' %>
    </div>

      <%= f.submit "Create Bandtogether", class: "btn btn-default btn-block"%>
    </div>
  <div class = "col-sm-4"></div>
</div>
<% end %>
<br>

app/views/bandtogethers/edit.html.erb
<h1>Editing Bandtogether</h1>

<%= render 'form' %>

<%= link_to 'Show', @bandtogether %> |
<%= link_to 'Back', bandtogethers_path %>

app/views/bandtogethers/index.html.erb
</div>
<p id="notice"><%= notice %></p>

<div class="jumbotron b2g_jumbo">
    <div class="jumbo col-sm-5">
      <div class="jumbo col-sm-5">
        <h1>Bandtogethers</h1>
      </div>
    </div>

</div>
<div class="container">
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Description</th>
      <th>Concert</th>
      <th>Organizer</th>
      <th>Attending</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% if !@bandtogethers.nil?%>
    <% @bandtogethers.each do |bandtogether| %>
      <tr>

        <td>
          <% if !bandtogether.bandtogether_avatar_file_name.nil? %>
            <%= image_tag(bandtogether.bandtogether_avatar.url(:thumb)) %>
          <% end %>
        </td>
        <td><a href = 'bandtogethers/<%=bandtogether.id %>'><%= bandtogether.title %></a></td>
        <td><%= bandtogether.start_time %></td>
        <td><%= bandtogether.end_time %></td>
        <td><%= bandtogether.description %></td>
        <td><%= bandtogether.concert.title %></td>
        <td><%= bandtogether.organizer.first_name %></td>
        <!-- Adding one to the membership count to include organizer -->
        <td><%=bandtogether.memberships.count + 1 %>
        <% if user_signed_in? %>
          <% if bandtogether.organizer_id == current_user.id || (current_user.has_role? :admin) %>
            <td><%= link_to 'Edit', edit_bandtogether_path(bandtogether) %></td>
            <td><%= link_to 'Destroy', bandtogether, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          <% end %>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<% if user_signed_in? %>
<%= link_to 'New Bandtogether', new_bandtogether_path %>
<% end %>

</div>

app/views/bandtogethers/invite.html.erb
<%= form_tag messages_path, method: :post do %>



<div class="form-group">
  <%= label_tag 'recipients', 'Choose recipients' %>
  <%= select_tag 'recipients', recipients_options(@chosen_recipient), multiple: true, class: 'form-control chosen-it' %>
</div>

  <div class="form-group">
    <%= label_tag 'message[subject]', 'Subject' %>
    <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true, value: current_user.first_name + ' invites you to a Bandtogether!' %>
  </div>

  <div class="form-group">
    <%= label_tag 'message[body]', 'Message' %>
    <%= text_area_tag 'message[body]', 'Go to this website to view this awesome event! http://localhost:3000/bandtogethers/' + @bandtogether.id.to_s , cols: 3, class: 'form-control', required: true %>
  </div>

  <%= submit_tag 'Send', class: 'btn btn-default' %>
<% end %>

app/views/bandtogethers/new.html.erb
<h1>New Bandtogether</h1>

<%= render 'form' %>

<%= link_to 'Back', bandtogethers_path %>

app/views/bandtogethers/show.html.erb
<p id="notice"><%= notice %></p>


<div class="panel panel-default">
  <div class="row title">
  <a href="/concerts/<%=@concert.id%>">Back to Concert</a>
    <h2>  <%= @bandtogether.title %> </h2>
    <div class="col-sm-7">


        <p>
        <strong>Concert:</strong>
        <%= @bandtogether.concert.title %>
      </p>
      <p>
        <strong>Start time:</strong>
        <%= @bandtogether.start_time %>
      </p>
      <p>
        <strong>End time:</strong>
        <%= @bandtogether.end_time %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @bandtogether.description %>
      </p>
      <br>
      <% if @bandtogether.organizer == current_user %>
      <%= link_to 'Edit Bandtogether', edit_bandtogether_path(@bandtogether) %>
      <% end %>
    </div>

    <p>
      <strong>Going:</strong>
      <!-- Adding one to the membership count to include organizer -->
      <%= @bandtogether.memberships.count + 1%>
    </p>
    <p>
      <li>
        <!--show oranizer name in list because they are automatically going whether they want to or not -->
        <a href="/users/<%= @bandtogether.organizer.id %>">
          <%= @bandtogether.organizer.first_name %>
          <%= @bandtogether.organizer.last_name %>
        </a> (Organizer)
      </li>
      <!--list each member by first name +last name -->
      <%@bandtogether.members.each do |member| %>
      <li><a href="/users/<%=member.id%>"> <%=member.first_name%> <%=member.last_name%></a></li>
      <%end%>
    </p>
    <div class="col-sm-5">

      <a class="btn btn-default invite-join-buttons" href="/bandtogethers/<%=@bandtogether.id%>/invite">Invite</a>
      <% if @bandtogether.organizer == current_user %>
      <%else%>
        <%= render 'components/join_button' %>
      <% end %>
      <% if !@bandtogether.bandtogether_avatar_file_name.nil? %>
      <div class="clearfix bandtogether-pic">
      <%= image_tag(@bandtogether.bandtogether_avatar.url(:medium), class: 'clearfix') %>
      </div>
      <% end %>
    </div>
    </div>
  </div>

    <div class="well">
    <div class="clearfix">
    <%= commontator_thread(@bandtogether) %>
    </div>
  </div>
    <br>